[clean_ip]
name = "Clean old ip from database"
command = "/bin/bash scripts/actions/clean_ip"
accepted_return_codes = [0]
description = "Remove obsolete IP from the database."

[clean_images]
name = "Clean old images"
command = "/bin/bash scripts/actions/clean_images"
accepted_return_codes = [0]
description = "Remove expired images."

[check_quota]
name = "Check disk quota"
command = "/bin/bash scripts/actions/check_quota"
accepted_return_codes = [0]
description = "Check the disk quota for images stored by Lutim."

[reset_default_config]
name = "Reset the config file and restore a default one."
command = "/bin/bash scripts/actions/reset_default_config \"lutim.conf\""
accepted_return_codes = [0]
description = "Reset the config file lutim.conf."


[reset_default_nginx]
name = "Reset the nginx config for this app."
command = "/bin/bash scripts/actions/reset_default_system nginx"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the nginx config for this app."

[reset_default_systemd]
name = "Reset the systemd config for this app."
command = "/bin/bash scripts/actions/reset_default_system systemd"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the systemd config for this app."


[reset_default_app]
name = "Reset the app with a default configuration."
command = "/bin/bash scripts/actions/reset_default_app"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Reset the app to its default configuration to try to fix potential issues.<br>This action won't remove any data added to the app.<br>However, if you have modified any configuration, it will be overwritten."
