[clean_ip]
name = "Clean old ip from database"
command = "/bin/bash scripts/actions/clean_ip"
accepted_return_codes = [0]
description = "Remove obsolete IP from the database."

[clean_images]
name = "Clean old images"
command = "/bin/bash scripts/actions/clean_images"
accepted_return_codes = [0]
description = "Remove expired images."

[check_quota]
name = "Check disk quota"
command = "/bin/bash scripts/actions/check_quota"
accepted_return_codes = [0]
description = "Check the disk quota for images stored by Lutim."

[reset_default_config]
name = "Reset the config file and restore a default one."
command = "/bin/bash scripts/actions/reset_default_config \"lutim.conf\""
accepted_return_codes = [0]
description = "Reset the config file lutim.conf."
