#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }
BEGIN { unshift @INC, "$FindBin::Bin/../local/lib/perl5" }
BEGIN { unshift @INC, "$FindBin::Bin/../local/lib/perl5/i486-linux-gnu-thread-multi-64int" }

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Mounter');
