#!/bin/bash

# Source app helpers
source /usr/share/yunohost/helpers

app=$1
added_users=$2
permission=$3
added_groups=$4

if [ "$app" == __APP__ ]; then
    if [ "$added_groups" = "visitors" ]; then
        ynh_app_setting_delete --app=$app --key=protected_regex
    fi
fi