#!/bin/bash

# Récupère les infos de l'application.
app=lutim
final_path=$(sudo yunohost app setting $app final_path)
domain=$(sudo yunohost app setting $app domain)


# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/$app
sudo mkdir -p "$backup_dir"

# Backup sources & data
sudo cp -a $final_path/. $backup_dir/sources

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf


# Copie des fichiers du script init
sudo cp -a /etc/init.d/lutim $backup_dir/init.d_lutim
sudo cp -a /etc/default/lutim $backup_dir/default_lutim

# Copie du fichier du cron
sudo cp -a /etc/cron.d/$app $backup_dir/cron_$app
