#!/bin/bash

# Récupère les infos de l'application.
app=$YNH_APP_INSTANCE_NAME

final_path=$(sudo yunohost app setting $app final_path)
domain=$(sudo yunohost app setting $app domain)
codename=$(sudo yunohost app setting $app codename)

# The parameter $1 is the uncompressed restore directory location
backup_dir=$1/apps/$app

# Restore sources & data
sudo cp -a $backup_dir/sources/. $final_path

# Restore Nginx and YunoHost parameters
sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf


if [ "$codename" = "wheezy" ]
then
	# Restauration des fichiers du script init
	sudo cp -a $backup_dir/init.d_lutim /etc/init.d/lutim
	sudo cp -a $backup_dir/default_lutim /etc/default/lutim
	## Démarrage auto du service
	sudo update-rc.d lutim defaults
else
	# Restauration des fichiers du script systemd
	sudo cp -a $backup_dir/lutim.service /etc/systemd/system/lutim.service
	## Démarrage auto du service
	sudo systemctl enable lutim.service
fi


# Restauration du fichier du cron
sudo cp -a $backup_dir/cron_$app /etc/cron.d/$app

# Making log symbolic link to /var/log
sudo mkdir -p /var/log/$app/
sudo touch /var/log/$app/production.log 
sudo chown www-data: /var/log/$app/production.log
# Restaure la configuration de logrotate
sudo cp -a $backup_dir/logrotate /etc/logrotate.d/$app

# Restart webserver
sudo service nginx reload

# Start lutim
sudo service lutim start
