#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================
ynh_script_progression --message="Retrieve arguments from the manifest"

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

#=================================================
# SPECIFIC ACTION
#=================================================
# CHECK THE DISK QUOTA FOR IMAGES STORED BY LUTIM
#=================================================
ynh_script_progression --message="Check the disk quota for images stored by lutim" --weight=9

(cd "$final_path" && $(which carton) exec script/lutim cron watch)

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
