#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

#=================================================
# SPECIFIC ACTION
#=================================================
# REMOVE OBSOLETE IP FROM THE DATABASE
#=================================================
ynh_script_progression --message="Removing obsolete ip from the database..." --weight=9

(cd "$final_path" && exec_as $app $(which carton) exec script/lutim cron cleanbdd)

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
